version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    dependencies-pip:
      patterns:
      - "*"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    dependencies-npm:
      patterns:
      - "*"
