version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "disabled"
  open-pull-requests-limit: 10
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "disabled"
  open-pull-requests-limit: 10
